// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyDiabeticSystem.Web.Data;

namespace MyDiabeticSystem.Web.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20191002002406_InitialDb")]
    partial class InitialDb
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.11-servicing-32099")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MyDiabeticSystem.Web.Data.Entities.Check", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("Bolus");

                    b.Property<double>("Carbohydrates");

                    b.Property<DateTime>("Date");

                    b.Property<double>("Glucometry");

                    b.Property<double>("Hb1");

                    b.HasKey("Id");

                    b.ToTable("Checks");
                });
#pragma warning restore 612, 618
        }
    }
}
